### ISSUE TITLE
GPU computing issues

### ISSUE THREAD

**Issue by ericle99** [MSSRSupport/MSSR#1]
Hello MSSR team! 

thank you for releasing this tool! I have done a rudimentary dataset on a cpu to test and it seems to work super well! 

Sadly I am running into and issue on both Mac and Windows when enabling GPU acceleration. Despite installing CLIJ (whose test macro runs fine) when I attempt to click on GPU computing in the MSSR window, the checkbox becomes unclickable and running MSSR fails unless I restart FIJI. I get error messages related to CLIJ, but figured this is likely an issue with MSSR since the aforementioned macro seems to be OK. 

I will try to update this post with the exact error message soon. 

Thanks again!

Editing: 

Found a work around, but was found by luck- still seems like there is a bug present. 

Steps to re-create workwound
1: load image
2: open MSSR analysis
3: click GPU computing (will get greyed out), log shows "in development"
4: close MSSR analysis
5: re-open MSSR analysis (GPU will be magically checked but says "no gpu" 
6: input parameters
7: run MSSR- This time it detects and uses GPU in log.

**Comment by RaulPintoC** [comment]
Hello, thanks for writing to us.
We already checked what the problem is and it is that the plugin is not detecting your available GPUs, this may be because we are not considering all the GPUs brands.
When the plugin does not detect any GPU, it places the option "No GPU" and the checkbox becomes unclickable, so you cant try to use the MSSR plugin in "GPU mode" without GPUs, the other problem is that there is a bug that causes the "GPU Computing" option to be reselected and since there are "no" GPUs, the process hangs and there are problems with CLIJ.


We are already working on a new public version of the plugin that fixes the bugs that have been found.
What we would need is for you to list the GPUs that you have on your PC, so we can add that GPUs brands.

**Comment by ericle99** [comment]
Hello and thank you for following up. 

This problem occurs with an Nvidia Quadro RTX 4000 and Nvidia A6000 GPU's.

**Comment by RaulPintoC** [comment]
Hello, in the new version of the plugin, this problem should be solved.
