### ISSUE TITLE
Usage with deconvolution

### ISSUE THREAD

**Issue by lguerard** [MSSRSupport/MSSR#3]
Hi all,

I tried getting the information from the paper but couldn't so I'm asking here.

Can MSSR be used on deconvolved images (from Huygens for instance) ? The paper says that MSSR is a deconvolution step but it's still applicable on Airyscan processed images which are deconvolved. Same for SRRF images...

From a theory perspective, is using MSSR authorized on deconvolved images if it's using a different approach for the deconvolution ?

Thanks for your help !

Looking forward to your reply !

**Comment by EsleyGit** [comment]
In regards to the first question, yes, MSSR can be used as a deconvolution process on fluorescent diffracted images. This is because MSSR effectively reduces the impact of the point spread function, improving the resolution and enhancing the quality of the images.
Regarding the second question, MSSR performs best when there is a black background in the image. It highlights the local brightest intensity based on the FWHM (full width at half maximum) value parameter. However, MSSR is not recommended for use on brightfield microscopy images, as these types of images do not typically have a black background and may not yield desirable results with MSSR.

**Comment by lguerard** [comment]
Hi, thanks to your reply.

However, I am not talking about brightfield images, but only fluorescent images. The question is:

Can MSSR be applied only on raw data or also on deconvolved images, as a 2nd processing step?

Thank you !

**Comment by EsleyGit** [comment]
Yes, absolutely.

If you have some problem with any image, just tell me. I will reply, as soon as I can.

**Comment by lguerard** [comment]
Super, thanks for the confirmation ! And is there any limit to the order and AMP then ? Or we can use any ?

**Comment by EsleyGit** [comment]
With amplification, the only limitation is the computation time. But can apply any natural number to increase the image.
The order has son disadvantages, higher order (greater than 3), can disappear some intensities. This is because MSSR prevails the global brightest intensity on the image. But this depends on the features of the image you are processing.  I recommend starting with zero-order amplification and evaluating the results. If the outcome is not good, then progressively higher orders can be applied to further enhance the image. 
It is important to consider that if the fluorophores are closer than the Sparrow limit, then you may not be able to uncover some structures. All of this is done by using single-frame MSSR.
